### ISSUE TITLE
the winfo-base-url did not change the PROPERTIY of Url

### ISSUE THREAD

**Issue by GTrunSec** [progfolio/wikinforg#1]
I changed the wikinfo-base-url to cn-wiki or jp-wiki.  but PROPERTIY of Url still in default url which is `en.wiki`

test jp.wiki
Value in
wikinfo-base-url
"https://jp.wikipedia.org"
output:
:URL:      https://en.wikipedia.org?curid=

**Comment by progfolio** [comment]
How and when are you changing the `wikinfo-base-url`?
Both of the following work correctly for me:

```emacs-lisp
(progn
  (setq wikinfo-base-url  "https://jp.wikipedia.org")
  (wikinforg t "test" #'car))
```

```emacs-lisp
(progn
  (require 'wikinforg)
  (let ((wikinfo-base-url "https://jp.wikipedia.org"))
    (wikinforg t "test" #'car)))
```

**Comment by GTrunSec** [comment]
sorry, my bad. I'm changing the default-URL via `dir-locals`. it was a different question that might be how to change the property of URL in `dir-locals`. thanks
```
  (eval . (setq-local wikinfo-base-url  "https://jp.wikipedia.org"))
```

**Comment by progfolio** [comment]
> sorry, my bad. I'm changing the default-URL via `dir-locals`. it was a different question that might be how to change the property of URL in `dir-locals`. thanks
> 
> ```
>   (eval . (setq-local wikinfo-base-url  "https://jp.wikipedia.org"))
> ```

Does that work for you?

**Comment by GTrunSec** [comment]
yes, it works (setq XXX)for me. but the `setq-local` does not. Do you have any idea how to set the property of URL in the local env instead of global? I would like to use EN-wiki as my default URL(global).

**Comment by progfolio** [comment]
Your dir-local lisp above looks malformed.
Try reading through this:
https://www.gnu.org/software/emacs/manual/html_node/emacs/Directory-Variables.html

There is also the `add-dir-local-variable` command which will prompt you for the directory/variable/value and correctly create the `.dir-locals` file.

**Comment by progfolio** [comment]
After running `add-dir-local-variable` this is the file I end up with:

```emacs-lisp
;;; Directory Local Variables
;;; For more information see (info "(emacs) Directory Variables")

((nil . ((wikinfo-base-url . "https://jp.wikipedia.org"))))
```
Which works on my end. The car of `nil` is explained in the docs I linked:

> Instead of a mode name, you can specify ‘nil’, which means that the alist applies to any mode;

**Comment by GTrunSec** [comment]
thanks for your answer.

**Comment by GTrunSec** [comment]
r

**Comment by GTrunSec** [comment]
I just make sure have you got the correct query URL which in your PROPERTIES?
but for me, nothing to be changed.
:URL:      https://en.wikipedia.org?curid=444444
that should be jp.wikipedia.org

**Comment by progfolio** [comment]
I see what you're saying now. You have successfully set the variable `wikinfo-base-url` but the value is not being reflected in the entry properties. That's probably due to the fact that the entry is constructed in a temporary buffer. Rather than do that, I think I can construct the entry using the `org-element` API. Let me see what I can do.

**Comment by progfolio** [comment]
Give f66abe3 a try. It should fix that for you.

**Comment by GTrunSec** [comment]
Thanks so much, it works for me.
