### ISSUE TITLE
Error when loading the infobox 

### ISSUE THREAD

**Issue by Enrico68** [progfolio/wikinforg#3]
When I tried to insert the article I get this error :

```
helm-M-x-execute-command: End of file while parsing JSON: "'[' or '{' expected near end of file", "<string>", 1, 0, 0
```

**Comment by progfolio** [comment]
I need the article you were trying to insert to debug this.

**Comment by Enrico68** [comment]
[Emacs](https://it.wikipedia.org/wiki/Emacs)

I have changed the language on the variable `Wikinforg Wikipedia Edition Code` to `it`

**Comment by progfolio** [comment]
[The Italian wikitext](https://it.wikipedia.org/w/index.php?title=Emacs&action=edit) doesn't appear to use the Infobox template.

```
{{Software
|Nome = Emacs
|Screenshot = Emacs GTK XFT.png
|DimensioneScreenshot = 250
|Didascalia = Screenshot di Emacs (versione Alpha con supporto librerie [[GTK+]] e [[Xft]] con [[antialiasing]]).
|Sviluppatore = 
|UltimaVersione =
|DataUltimaVersione =
|SistemaOperativo = gnu project
|SistemaOperativo2 = windows
|SistemaOperativo3 = macOS
|SistemaOperativoAltri = TECO
|Linguaggio = Lisp 
|Linguaggio2 = c
|Genere = Editor di testo
|Licenza = [[GNU General Public License|GPLv3+]]
|Lingua = 
|SoftwareLibero = sì
|SitoWeb = 
}}
```

See [the English wikitext](https://en.wikipedia.org/w/index.php?title=Emacs&action=edit) for comparison. Note the difference in the first line between the two.

```
{{Infobox software
| name = Emacs
| screenshot = Emacs27_showing_Org,_Magit,_and_Dired_with_the_modus-operandi_theme.png
| caption = [[Org-mode]], [[Magit]], and [[Dired]] buffers in [[GNU Emacs]]
| author = [[David A. Moon]],<br/>[[Guy L. Steele Jr.]]
| developer = Various [[free software|free/libre software]] developers, including volunteers and [[commercial software|commercial]] developers
| released = {{Start date and age|df=yes|1976}}<ref>{{cite web|url=https://www.emacswiki.org/emacs/EmacsReleaseDates|title=Emacs Release Dates}}</ref><ref name=jwz_timeline>
{{cite web|title=Emacs Timeline|url=http://www.jwz.org/doc/emacs-timeline.html|access-date=11 August 2015 | last = Zawinski | first = Jamie | author-link = Jamie Zawinski | date = 2005-06-21 |orig-year=1999 }}</ref>
| latest release version = <!-- Please don't place a version here, as this article is about all editors in the EMACS family.  Instead, you may wish to update or add version information to specific software project articles. -->
| latest release date = <!-- Please don't place a version here, as this article is about all editors in the EMACS family.  Instead, you may wish to update or add version information to specific software project articles. -->
| latest preview version = 
| latest preview date = 
| operating system = [[Cross-platform]]
| programming language = [[Lisp (programming language)|Lisp]], [[C (programming language)|C]]
| genre = [[Text editor]]
| license = 
}}
```

Ideally, results which do not contain infoboxes shouldn't be presented to the user. I pushed a change a few months ago to the development branch which changed how we look for infoboxes, but I forgot to push it to the master branch of the library wikinforg is built on. I've pushed that change now. If you're using MELPA to download the package, that change should be live in an hour or so. You should get a "Query failed" user-error in the case described above.

Unfortunately, there's not much I can do if the wikitext doesn't have "Infobox" in it (unless there is a better way to query wikipedia's API, which I'm not aware of).

**Comment by Enrico68** [comment]
Ah, that's I didn't know. Is there which languages support the infobox ? Anyway, thanks for your useful package !

**Comment by progfolio** [comment]
> Is there which languages support the infobox ? 

It's not language specific. It's article specific. Whoever edits the wikitext decides which templates to use. Since it is Wikipedia, anyone could edit them.

> thanks for your useful package !

You're welcome.
