### ISSUE TITLE
[FEATURE REQUEST] Support for buffer level

### ISSUE THREAD

**Issue by Cletip** [progfolio/wikinforg#4]
Hello,

First of all, I would like to thank you for this package, I find it really nice.

I wanted to ask the following question : could it work on buffer level, and not on org-heading level ? It would be practical for org-roam for example.

Thank you in advance for your answer and good continuation

**Comment by progfolio** [comment]
Hi. Glad you're finding wikinforg useful.
Let me make sure I understand the request correctly.
Assuming such a feature is added, the output would be formatted like so?:

```
:PROPERTIES:
:industry: Aerospace
:defunct:  5 May 2010
:headquarters: Brno, Czech Republic
:products: Gliders
:website:  www.lsa-gliders.com
:thumbnail: https://upload.wikimedia.org/wikipedia/en/f/f3/TeST_Logo.png
:wikinfo-id: 24884283
:URL:      https://en.wikipedia.org?curid=24884283
:END:
#+title: TeST Gliders

[[file:/tmp/wikinforg/TeST_Logo.png]]

TeST Gliders is a manufacturer of ultralight sailplanes and motorgliders based in Brno, Czech Republic.
```

**Comment by Cletip** [comment]
Yhea, that is exactly what I was thinking

**Comment by progfolio** [comment]
I've added a `buffer` option for `wikinforg-data-type`.

``` emacs-lisp
(require 'wikinforg)
(let ((wikinforg-data-type 'buffer))
  (wikinforg "Lisp program" #'car t))
```

produces the following output:

``` org
:PROPERTIES:
:paradigm: Multi-paradigm: functional, procedural, reflective, meta
:designed-by: John McCarthy
:developer: Steve Russell, Timothy P. Hart, and Mike Levin
:first-appeared: 1958; 64 years ago (1958)
:typing-discipline: Dynamic, strong
:thumbnail: https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Lisp_logo.svg/120px-Lisp_logo.svg.png
:wikinfo-id: 18016
:URL:      https://en.wikipedia.org?curid=18016
:END:
#+title: Lisp (programming language)

[[file:/tmp/wikinforg/120px-Lisp_logo.svg.png]]

Lisp (historically LISP) is a family of programming languages with a long history and a distinctive, fully parenthesized prefix notation. Originally specified in 1958, Lisp is the second-oldest high-level programming language still in common use. Only Fortran is older, by one year.
```

I also refactored the wikinforg function and made some changes to its signature. This shouldn't affect anything unless you were calling it programmatically.

Let me know if that works for you.

**Comment by Cletip** [comment]
Sorry for my late reply.

It seems to work perfectly for me ! Thank you for this.

**Comment by thomfranco** [comment]
Oh, hi! Thank you for the package, it's awesome!

I was looking for a solution similar to this. In my use-case, all the buffer level properties are inserted as top-level org keywords (like `#+title`). So, the output would look like this:

```
#+title: Lisp (programming language)
#+paradigm: Multi-paradigm: functional, procedural, reflective, meta
#+designed-by: John McCarthy
#+developer: Steve Russell, Timothy P. Hart, and Mike Levin
#+first-appeared: 1958; 64 years ago (1958)
#+typing-discipline: Dynamic, strong
#+thumbnail: https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Lisp_logo.svg/120px-Lisp_logo.svg.png
#+wikinfo-id: 18016
#+URL:      https://en.wikipedia.org?curid=18016
```
I currently do this manually. So, could this be a option in `wikinforg-data-type` also?
