### ISSUE TITLE
Change the language of the infobox

### ISSUE THREAD

**Issue by Cletip** [progfolio/wikinforg#5]
Hello,
I tried to change the language like this: 
`(setq wikinfo-base-url "https://fr.wikipedia.org")`

but, it doesn't work, the output is always "Contacting host: en.wikipedia.org:443"

Can we change the language of the request ?

**Comment by progfolio** [comment]
Please see  the `wikinforg-wikipedia-edition-code` customization option.

**Comment by Cletip** [comment]
Sorry late reply. 

It's just perfect ! In addition (this is the first time I've done it), but I have different proposals if the request is not precise enough. That's great, thank you very much!
