### ISSUE TITLE
Retrieve the "type" of the infobox

### ISSUE THREAD

**Issue by Cletip** [progfolio/wikinforg#6]
Hello. Sorry, I ask this question without having looked in detail at the code, but I think you know the answer directly: is it possible to recover the "type" of the infobox?
For example, on this page https://fr.wikipedia.org/?curid=1041, the type of the infobox is "Software".
To know the type, click on the i at the bottom right of the infobox.

I would like, if possible, to retrieve this type. Would you know how to do it? This is maybe a variable in your code ?

Thank you in advance for your futur answer

**Comment by progfolio** [comment]
The library wikinforg uses, wikinfo, works by parsing the rendered HTML of the infobox.
The template type is not usually available there (to my knowledge). 
That's not to say it couldn't be done via `wikinforg-post-insert-hook` or by advising the right function,  but I won't be adding it as a supported feature.
